# Generated by Django 4.2.3 on 2023-07-21 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KueIndonesia',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('prediction', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
